In [43]:
import pandas as pd
import numpy as np

In [44]:
df=pd.read_csv('Churn_modelling.csv')
df

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [46]:
df.duplicated().sum()

0

In [47]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [48]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [49]:
df.drop(columns=['RowNumber','CustomerId','Surname'],inplace=True)
df

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0             1               1        101348.88       1  
1             0               1        112542.58       0  
2             1               0        113931.57       1  
3             0               0         93826.63       0  
4             1               1         79084.10       0  
...         ...             ...              ...     ...  
9995          1               0         96270.64       0  
9996          1               1        101699.77       0  
9997          0               1         42085.58       1  
9998          1               0         92888.52       1  
9999          1               0         38190.78       0  

[10000 rows x 11 columns]

In [50]:
df=pd.get_dummies(df,columns=['Geography','Gender'],drop_first=True)
df

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Exited  Geography_Germany  \
0                  1        101348.88       1              False   
1                  1        112542.58       0              False   
2                  0        113931.57       1              False   
3                  0         93826.63       0              False   
4                  1         79084.10       0              False   
...              ...              ...     ...                ...   
9995               0         96270.64       0              False   
9996               1        101699.77       0              False   
9997               1         42085.58       1              False   
9998               0         92888.52       1               True   
9999               0         38190.78       0              False   

      Geography_Spain  Gender_Male  
0               False        False  
1                True        False  
2               False        False  
3               False        False  
4                True        False  
...               ...          ...  
9995            False         True  
9996            False         True  
9997            False        False  
9998            False         True  
9999            False        False  

[10000 rows x 12 columns]

In [51]:

X=df.drop(columns=["Exited"])
Y=df["Exited"]
from sklearn.model_selection import train_test_split
X_train,X_test,Y_Train,Y_Test=train_test_split(X,Y,test_size=0.2)
X

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Geography_Germany  Geography_Spain  \
0                  1        101348.88              False            False   
1                  1        112542.58              False             True   
2                  0        113931.57              False            False   
3                  0         93826.63              False            False   
4                  1         79084.10              False             True   
...              ...              ...                ...              ...   
9995               0         96270.64              False            False   
9996               1        101699.77              False            False   
9997               1         42085.58              False            False   
9998               0         92888.52               True            False   
9999               0         38190.78              False            False   

      Gender_Male  
0           False  
1           False  
2           False  
3           False  
4           False  
...           ...  
9995         True  
9996         True  
9997        False  
9998         True  
9999        False  

[10000 rows x 11 columns]

In [52]:
from sklearn.preprocessing import StandardScaler
Scaler=StandardScaler()
X_train_scale=Scaler.fit_transform(X_train)
X_test_scale=Scaler.transform(X_test)
X_test_scale


array([[ 0.33801567,  0.47873388, -1.04751782, ...,  1.73147365,
        -0.57696537, -1.09997489],
       [-0.51827523,  0.38401481,  1.02737408, ..., -0.57754272,
        -0.57696537, -1.09997489],
       [ 0.17294755,  1.61536278,  1.37318939, ...,  1.73147365,
        -0.57696537,  0.90911166],
       ...,
       [ 0.99828818, -0.56317594, -1.39333314, ..., -0.57754272,
        -0.57696537,  0.90911166],
       [-0.12623843, -0.37373779,  1.02737408, ..., -0.57754272,
        -0.57696537,  0.90911166],
       [ 1.18398982, -1.03677131, -0.7017025 , ...,  1.73147365,
        -0.57696537, -1.09997489]])

In [56]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

In [57]:
model=Sequential()
model.add(Dense(3,activation='sigmoid',input_dim=11))
model.add(Dense(1,activation='sigmoid'))
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 36        
                                                                 
 dense_1 (Dense)             (None, 1)                 4         
                                                                 
Total params: 40 (160.00 Byte)
Trainable params: 40 (160.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [59]:
model.compile(loss='binary_crossentropy',optimizer='Adam')
model.fit(X_train_scale,Y_Train,epochs=10)

Epoch 1/10

250/250 [==============================] - 5s 6ms/step - loss: 0.8742
Epoch 2/10
250/250 [==============================] - 1s 4ms/step - loss: 0.6562
Epoch 3/10
250/250 [==============================] - 1s 4ms/step - loss: 0.5484
Epoch 4/10
250/250 [==============================] - 1s 3ms/step - loss: 0.4991
Epoch 5/10
250/250 [==============================] - 1s 3ms/step - loss: 0.4763
Epoch 6/10
250/250 [==============================] - 1s 5ms/step - loss: 0.4645
Epoch 7/10
250/250 [==============================] - 1s 4ms/step - loss: 0.4569
Epoch 8/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4510
Epoch 9/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4459
Epoch 10/10
250/250 [==============================] - 1s 2ms/step - loss: 0.4413


In [60]:
model.layers[0].get_weights()

[array([[-0.4318365 , -0.08400892, -0.00479245],
        [ 0.7007733 , -1.6761845 ,  0.5044865 ],
        [-0.08098203,  0.07598037, -0.3909138 ],
        [ 0.59073794, -0.21615367,  0.47202572],
        [ 0.09351382,  0.04561805, -0.93934435],
        [-0.27122772, -0.00627391,  0.3221039 ],
        [-0.6159524 ,  0.7439655 , -0.5448147 ],
        [ 0.07608654, -0.01104151,  0.28273246],
        [ 0.33957937, -0.70612293, -0.05242724],
        [-0.24684988, -0.01822708, -0.22152273],
        [-0.26593885,  0.49394622, -0.31495136]], dtype=float32),
 array([-0.59207743,  0.9422562 , -0.5560683 ], dtype=float32)]

In [61]:
model.layers[1].get_weights()

[array([[ 0.56488127],
        [-1.46288   ],
        [ 0.2954102 ]], dtype=float32),
 array([-0.81033885], dtype=float32)]

In [68]:
y_log=model.predict(X_test_scale)

63/63 [==============================] - 0s 3ms/step


In [69]:
y_pred=np.where(y_log>0.5,1,0)

In [70]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_Test,y_pred)

0.807